name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    # 💡 Cloudflare用にURLを「/」のままにするため、ここにあったsedコマンドのステップを削除しました。

    - name: Publish Website
      run: dotnet publish BarcodeAlertApp.csproj -c Release -o release

    - name: Copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: release/wwwroot
        branch: gh-pages